apiVersion: apps/v1
kind: Deployment
metadata:
  name: pesbuk
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pesbuk
      metadata: pesbuk
  template:
    metadata:
      labels:
        name: pesbuk
        metadata: pesbuk
    spec:
      containers:
      - name: pesbuk
        image: arizki/pesbuk:branch-appversion
        ports:
          - containerPort: 80
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: secretpesbuk
                key: DB_USER
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: secretpesbuk
                key: DB_PASS
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: secretpesbuk
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: secretpesbuk
                key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: pesbuk
<<<<<<< HEAD
  namespace: production
=======
  namespace: staging
>>>>>>> 87249d2aa2af84f7d03043fbc973914ddfbf0894
spec:
  #type: LoadBalancer
  ports:
    - port: 80
      #nodePort: 30080
  selector:
    name: pesbuk
---
